# podman-compose.yml
# Ryan Loiselle — Developer / Architect
# GitHub Copilot — AI pair programmer / code generation
# February 2026
#
# AI-assisted: local multi-container development setup mirroring BC Gov OpenShift layout;
# reviewed and directed by Ryan Loiselle.
#
# Replace <PROJECT_NAME> with the actual project name.
# Replace DB_NAME, DB_USER, DB_PASSWORD with project-specific values.
#
# Usage:
#   podman-compose up --build        # build and start all services
#   podman-compose down -v           # stop and remove volumes
#   podman-compose logs -f api       # tail API logs

version: '3.8'

services:

  # ── DATABASE ─────────────────────────────────────────────────────────────────
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root_dev_password
      MYSQL_DATABASE: <DB_NAME>
      MYSQL_USER: <DB_USER>
      MYSQL_PASSWORD: <DB_PASSWORD>
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # ── API ──────────────────────────────────────────────────────────────────────
  api:
    build:
      context: ..
      dockerfile: containerization/Containerfile.api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=<DB_NAME>;User=<DB_USER>;Password=<DB_PASSWORD>;
      # Override to bypass X-Admin-Token check in local development
      - Authentication__BypassAuth=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # ── FRONTEND ──────────────────────────────────────────────────────────────────
  frontend:
    build:
      context: ..
      dockerfile: containerization/Containerfile.frontend
    ports:
      - "5173:8080"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
